name: Check formatting with raco fmt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo add-apt-repository ppa:plt/racket
        sudo apt-get update
        sudo apt-get install -y racket
        raco pkg install --no-docs --deps search-auto --batch fmt
    - run: |
        raco fmt -i racket/*.rkt
        [ -z "$(git status --porcelain)" ]