name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt-get install -y racket
        raco pkg install --no-docs --deps search-auto --batch fmt
        raco fmt *.rkt
        [ -z "$(git status --porcelain)"]

  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        export TAG=lakeroad:$(date +%s)
        DOCKER_BUILDKIT=1 docker build \
          . \
          --file Dockerfile \
          --tag $TAG
        docker run $TAG bash -c 'raco test *.rkt'
