name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.build.output.tag }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      id: build
      run: |
        export TAG=lakeroad:$(date +%s)
        echo "::set-output name=tag::$TAG"
        docker build \
          . \
          --file Dockerfile \
          --tag $TAG

  check-fmt:
    runs-on: ubuntu-latest
    needs: build
    steps:
      run: docker run ${{ needs.build.outputs.tag }} bash -c 'raco pkg install --batch fmt && raco fmt *.rkt && [ -z "$(git status --porcelain)"]'

  run-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run the experiment
      run: docker run ${{ needs.build.outputs.tag }} bash -c 'raco test *.rkt'
