name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      id: build
      run: |
        export TAG=lakeroad:$(date +%s)
        echo "::set-output name=TAG::$TAG"
        docker build \
          . \
          --file Dockerfile \
          --tag $TAG
    - name: Run the experiment
      run: docker run ${{ steps.build.outputs.TAG }} raco test *.rkt
