name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        export TAG=lakeroad:$(date +%s)
        echo "::set-output name=TAG::$TAG"
        docker build \
          . \
          --file Dockerfile \
          --tag $TAG
    - name: Run the experiment
      run: docker run racket experiment.rkt
