name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # TODO(@gussmith23) It would be nice if this wasn't necessary
  cleaner:
    runs-on: self-hosted
    steps:
      - name: Clean up previous runs
        run: rm -rf "${{ github.workspace }}"

  run-tests:
    runs-on: self-hosted
    # Make sure we clean first.
    needs: cleaner
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - id: build
      run: |
        export TAG=lakeroad:$(date +%s)
        echo "::set-output name=tag::$TAG"
    - name: Build Docker image
      run: |
        DOCKER_BUILDKIT=1 docker build \
          . \
          --file Dockerfile \
          --tag ${{ steps.build.outputs.tag }}
    - name: Run tests
      run: docker run ${{ steps.build.outputs.tag }} bash run-tests.sh
